// fitness-tracker/client/src/pages/ExerciseTypes.jsx
import { useEffect, useState } from 'react';
import API from '../services/api';
import '../styles/SharedStyles.css';

const ExerciseTypes = () => {
  const [exerciseTypes, setExerciseTypes] = useState([]);
  const [newType, setNewType] = useState({ name: '', category: '' });

  useEffect(() => {
    fetchExerciseTypes();
  }, []);

  const fetchExerciseTypes = async () => {
    try {
      const res = await API.get('/exercise-types');
      setExerciseTypes(res.data);
    } catch (e) {
      alert('Failed to fetch exercise types: ' + e.message);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      const res = await API.post('/exercise-types', newType);
      setExerciseTypes([...exerciseTypes, res.data]);
      setNewType({ name: '', category: '' });
    } catch (e) {
      alert('Failed to add exercise type: ' + e.message);
    }
  };

  return (
    <div className="page-container">
      <h2>Manage Exercise Types</h2>
      <form onSubmit={handleSubmit} className="form-box">
        <input
          type="text"
          placeholder="Name"
          value={newType.name}
          onChange={(e) => setNewType({ ...newType, name: e.target.value })}
          required
          className="input-field"
        />
        <input
          type="text"
          placeholder="Category"
          value={newType.category}
          onChange={(e) => setNewType({ ...newType, category: e.target.value })}
          required
          className="input-field"
        />
        <button type="submit" className="button-primary">Add Exercise Type</button>
      </form>

      <ul className="list-reset">
        {exerciseTypes.map((type) => (
          <li key={type._id} className="list-item">
            <strong>{type.name}</strong> – Category: {type.category}
          </li>
        ))}
      </ul>

      {exerciseTypes.length === 0 && <p>No exercise types defined yet.</p>}
    </div>
  );
};

export default ExerciseTypes;

// fitness-tracker/client/src/views/ExerciseTypes.vue
<template>
  <div>
    <h2>Exercise Types</h2>
    <button @click="showCreateForm = !showCreateForm">Create Exercise Type</button>

    <form v-if="showCreateForm" @submit.prevent="createExerciseType">
      <input v-model="newExerciseType.name" placeholder="Exercise Type" required />
      <button type="submit">Create</button>
    </form>

    <ul v-if="exerciseTypes.length">
      <li v-for="exercise in exerciseTypes" :key="exercise._id">
        {{ exercise.name }}
        <button @click="editExerciseType(exercise)">Edit</button>
        <button @click="deleteExerciseType(exercise._id)">Delete</button>
      </li>
    </ul>

    <form v-if="editingExerciseType" @submit.prevent="updateExerciseType">
      <input v-model="editingExerciseType.name" required />
      <button type="submit">Update</button>
      <button @click="cancelEdit">Cancel</button>
    </form>
  </div>
</template>

<script>
import API from '@/services/api';

export default {
  name: 'ExerciseTypes',
  data() {
    return {
      exerciseTypes: [],
      newExerciseType: { name: '' },
      editingExerciseType: null,
      showCreateForm: false,
    };
  },
  methods: {
    async fetchExerciseTypes() {
      const res = await API.get('/exercise-types');
      this.exerciseTypes = res.data;
    },
    async createExerciseType() {
      await API.post('/exercise-types', this.newExerciseType);
      this.newExerciseType.name = '';
      this.fetchExerciseTypes();
    },
    async updateExerciseType() {
      await API.put(`/exercise-types/${this.editingExerciseType._id}`, this.editingExerciseType);
      this.editingExerciseType = null;
      this.fetchExerciseTypes();
    },
    async deleteExerciseType(id) {
      await API.delete(`/exercise-types/${id}`);
      this.fetchExerciseTypes();
    },
    editExerciseType(type) {
      this.editingExerciseType = { ...type };
    },
    cancelEdit() {
      this.editingExerciseType = null;
    },
  },
  created() {
    this.fetchExerciseTypes();
  },
};
</script>
