// fitness-tracker/client/src/views/Activities.vue
<template>
  <div>
    <h2>Activities</h2>
    <button @click="showCreateForm = !showCreateForm">Create Activity</button>

    <form v-if="showCreateForm" @submit.prevent="createActivity">
      <input v-model="newActivity.name" placeholder="Name" required />
      <input v-model="newActivity.duration" type="number" placeholder="Duration (mins)" required />
      <input v-model="newActivity.calories" type="number" placeholder="Calories" required />
      <button type="submit">Create</button>
    </form>

    <ul v-if="activities.length">
      <li v-for="activity in activities" :key="activity._id">
        {{ activity.name }} - {{ activity.duration }} mins, {{ activity.calories }} kcal
        <button @click="editActivity(activity)">Edit</button>
        <button @click="deleteActivity(activity._id)">Delete</button>
      </li>
    </ul>

    <form v-if="editingActivity" @submit.prevent="updateActivity">
      <input v-model="editingActivity.name" required />
      <input v-model="editingActivity.duration" type="number" required />
      <input v-model="editingActivity.calories" type="number" required />
      <button type="submit">Update</button>
      <button @click="cancelEdit">Cancel</button>
    </form>
  </div>
</template>

<script>
import API from '@/services/api';

export default {
  name: 'Activities',
  data() {
    return {
      activities: [],
      newActivity: { name: '', duration: '', calories: '' },
      editingActivity: null,
      showCreateForm: false,
    };
  },
  methods: {
    async fetchActivities() {
      const res = await API.get('/activities');
      this.activities = res.data;
    },
    async createActivity() {
      await API.post('/activities', this.newActivity);
      this.newActivity = { name: '', duration: '', calories: '' };
      this.fetchActivities();
    },
    async updateActivity() {
      await API.put(`/activities/${this.editingActivity._id}`, this.editingActivity);
      this.editingActivity = null;
      this.fetchActivities();
    },
    async deleteActivity(id) {
      await API.delete(`/activities/${id}`);
      this.fetchActivities();
    },
    editActivity(activity) {
      this.editingActivity = { ...activity };
    },
    cancelEdit() {
      this.editingActivity = null;
    },
  },
  created() {
    this.fetchActivities();
  },
};
</script>

// fitness-tracker/client/src/pages/Activities.jsx
import { useEffect, useState } from 'react';
import API from '../services/api';
import '../styles/SharedStyles.css';

const Activities = () => {
  const [activities, setActivities] = useState([]);
  const [exerciseTypes, setExerciseTypes] = useState([]);
  const [newActivity, setNewActivity] = useState({
    type: '',
    duration: '',
    date: '',
  });

  useEffect(() => {
    fetchActivities();
    fetchExerciseTypes();
  }, []);

  const fetchActivities = async () => {
    try {
      const res = await API.get('/activities');
      setActivities(res.data);
    } catch (e) {
      alert('Failed to fetch activities: ' + e.message);
    }
  };

  const fetchExerciseTypes = async () => {
    try {
      const res = await API.get('/exercise-types');
      setExerciseTypes(res.data);
    } catch (e) {
      alert('Failed to fetch exercise types: ' + e.message);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      const res = await API.post('/activities', newActivity);
      setActivities([...activities, res.data]);
      setNewActivity({ type: '', duration: '', date: '' });
    } catch (e) {
      alert('Failed to add activity: ' + e.message);
    }
  };

  return (
    <div className="page-container">
      <h2>Manage Activities</h2>
      <form onSubmit={handleSubmit} className="form-box">
        <select
          value={newActivity.type}
          onChange={(e) => setNewActivity({ ...newActivity, type: e.target.value })}
          required
          className="input-field"
        >
          <option value="" disabled>Select Exercise Type</option>
          {exerciseTypes.map((et) => (
            <option key={et._id} value={et.name}>{et.name}</option>
          ))}
        </select>
        <input
          type="number"
          placeholder="Duration (minutes)"
          value={newActivity.duration}
          onChange={(e) => setNewActivity({ ...newActivity, duration: e.target.value })}
          required
          className="input-field"
        />
        <input
          type="date"
          value={newActivity.date}
          onChange={(e) => setNewActivity({ ...newActivity, date: e.target.value })}
          required
          className="input-field"
        />
        <button type="submit" className="button-primary">Add Activity</button>
      </form>

      <ul className="list-reset">
        {activities.map((a) => (
          <li key={a._id} className="list-item">
            {a.date}: <strong>{a.type}</strong> – {a.duration} minutes
          </li>
        ))}
      </ul>

      {activities.length === 0 && <p>No activities logged yet.</p>}
    </div>
  );
};

export default Activities;
